// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbLzeQoD46etRUQwO23QhJKI0Baebyuvw',
    appId: '1:1060729296116:web:27263ed5edf833ff1a3aa1',
    messagingSenderId: '1060729296116',
    projectId: 'myportfolio-e9741',
    authDomain: 'myportfolio-e9741.firebaseapp.com',
    storageBucket: 'myportfolio-e9741.firebasestorage.app',
    measurementId: 'G-YBHH8B5H6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNz028fMl3Jf5iYslBx5RTSTnpDhUkmo',
    appId: '1:1060729296116:android:177cca63d9474db31a3aa1',
    messagingSenderId: '1060729296116',
    projectId: 'myportfolio-e9741',
    storageBucket: 'myportfolio-e9741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0tliTDRVMW7YskpTd4jnGK2IvU2YGLOM',
    appId: '1:1060729296116:ios:57e17b571a5d63521a3aa1',
    messagingSenderId: '1060729296116',
    projectId: 'myportfolio-e9741',
    storageBucket: 'myportfolio-e9741.firebasestorage.app',
    iosClientId: '1060729296116-ntsaek03sul3qfdt1d0sub22kcp9c8gv.apps.googleusercontent.com',
    iosBundleId: 'com.hummingbird.amnetworks',
  );
}
