name: Flutter Web CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - uses: actions/checkout@v3

      # 2. Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Get dependencies
      - name: Get packages
        run: flutter pub get

      # 4. Build the web release
      - name: Build Web Release
        run: flutter build web --release --base-href "/amnetworks/"

      # 5. Deploy to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
